export type Admit = {
  year: 2025 | 2026;
  university: string;
  major: string;
  name: string;
  school: string;
};

/** 포스터 명단 그대로. 이름 가운데는 가림 처리. */
export const admits: Admit[] = [
  { year: 2025, university: "서울대학교", major: "체육교육과", name: "이O협", school: "평택고" },
  { year: 2025, university: "한국외국어대학교", major: "글로벌스포츠산업학부", name: "주O성", school: "솔샘고" },
  { year: 2025, university: "국민대학교", major: "스포츠산업레저학과", name: "김O현", school: "신현고" },
  { year: 2025, university: "국민대학교", major: "스포츠산업레저학과", name: "이O주", school: "휘봉고" },
  { year: 2025, university: "국민대학교", major: "스포츠산업레저학과", name: "최O진", school: "계성고" },
  { year: 2025, university: "인천대학교", major: "체육교육과", name: "주O성", school: "솔샘고" },
  { year: 2025, university: "서울과학기술대학교", major: "스포츠과학과", name: "김O호", school: "구미고" },
  { year: 2025, university: "한국체육대학교", major: "사회체육학과", name: "김O준", school: "송곡고" },
  { year: 2025, university: "서경대학교", major: "스포츠앤테크놀로지", name: "박O슬", school: "청량고" },
  { year: 2025, university: "성신여자대학교", major: "운동재활전공", name: "구O원", school: "신현고" },
  { year: 2025, university: "성신여자대학교", major: "운동재활전공", name: "김O민", school: "한성여고" },
  { year: 2025, university: "삼육대학교", major: "체육학과", name: "공O훈", school: "용문고" },
  { year: 2025, university: "삼육대학교", major: "체육학과", name: "백O서", school: "성신여고" },
  { year: 2025, university: "삼육대학교", major: "체육학과", name: "한O희", school: "경신고" },
  { year: 2025, university: "경기대학교", major: "체육학과", name: "김O현", school: "신현고" },
  { year: 2025, university: "경기대학교", major: "체육학과", name: "박O민", school: "무학여고" },
  { year: 2025, university: "경기대학교", major: "스포츠과학과", name: "구O원", school: "리라아트고" },
  { year: 2025, university: "경기대학교", major: "스포츠과학과", name: "이O주", school: "휘봉고" },
  { year: 2025, university: "단국대학교", major: "스포츠경영학과", name: "김O준", school: "송곡고" },
  { year: 2025, university: "단국대학교", major: "스포츠경영학과", name: "이O민", school: "송곡고" },
  { year: 2025, university: "상명대학교", major: "스포츠융합자유전공", name: "김O화", school: "계성고" },
  { year: 2025, university: "상명대학교", major: "스포츠융합자유전공", name: "유O희", school: "해성여고" },
  { year: 2025, university: "상명대학교", major: "스포츠융합자유전공", name: "이O민", school: "송곡고" },
  { year: 2025, university: "명지전문대학교", major: "사회체육과", name: "김O희", school: "해성여고" },
  { year: 2025, university: "명지전문대학교", major: "사회체육과", name: "연O모", school: "장충고" },
  { year: 2025, university: "명지전문대학교", major: "사회체육과", name: "이O훈", school: "경신고" },
  { year: 2025, university: "명지전문대학교", major: "사회체육과", name: "장O성", school: "고대부고" },
  { year: 2025, university: "서울시립대학교", major: "스포츠과학과", name: "김O원", school: "성신여고" },
  { year: 2025, university: "서울시립대학교", major: "스포츠과학과", name: "이O인", school: "성신여고" },
  { year: 2025, university: "인하대학교", major: "체육교육과", name: "주O성", school: "솔샘고" },
  { year: 2025, university: "세종대학교", major: "체육학과", name: "김O준", school: "송곡고" },
  { year: 2025, university: "세종대학교", major: "체육학과", name: "조O민", school: "삼각산고" },
  { year: 2025, university: "광운대학교", major: "스포츠융합과학과", name: "구O원", school: "신현고" },
  { year: 2025, university: "광운대학교", major: "스포츠융합과학과", name: "김O현", school: "신현고" },
  { year: 2025, university: "광운대학교", major: "스포츠융합과학과", name: "이O린", school: "솔샘고" },
  { year: 2025, university: "광운대학교", major: "스포츠융합과학과", name: "이O민", school: "신일고" },
  { year: 2025, university: "서원대학교", major: "체육교육과", name: "주O성", school: "솔샘고" },
  { year: 2025, university: "동덕여자대학교", major: "체육학과", name: "구O원", school: "신현고" },
  { year: 2025, university: "동덕여자대학교", major: "체육학과", name: "최O서", school: "한성여고" },
  { year: 2025, university: "덕성여자대학교", major: "생활체육학전공", name: "김O민", school: "신현고" },
  { year: 2025, university: "용인대학교", major: "특수체육교육과", name: "황O우", school: "한성고" },
  { year: 2025, university: "용인대학교", major: "체육학과", name: "백O서", school: "성신여고" },
  { year: 2025, university: "수원대학교", major: "스포츠과학부", name: "김O수", school: "고대부고" },
  { year: 2025, university: "수원대학교", major: "스포츠과학부", name: "이O서", school: "계성고" },
  { year: 2025, university: "수원대학교", major: "스포츠과학부", name: "정O영", school: "경신고" },
  { year: 2025, university: "백석대학교", major: "스포츠과학", name: "박O슬", school: "청량고" },
  { year: 2025, university: "대진대학교", major: "스포츠건강과학과", name: "김O린", school: "리라아트고" },
  { year: 2025, university: "대진대학교", major: "스포츠건강과학과", name: "박O슬", school: "청량고" },
  { year: 2025, university: "상지대학교", major: "체육학전공", name: "나O웅", school: "대경고" },
  { year: 2025, university: "한양여자대학교", major: "스포츠건강관리과", name: "김O민", school: "신현고" },
  { year: 2025, university: "한양여자대학교", major: "스포츠건강관리과", name: "최O민", school: "삼각산고" },
  { year: 2025, university: "경민대학교", major: "레포츠과", name: "강O성", school: "리라아트고" },
  { year: 2025, university: "경민대학교", major: "레포츠과", name: "장O성", school: "고대부고" },
  { year: 2025, university: "경민대학교", major: "레포츠과", name: "최O영", school: "삼각산고" },

  { year: 2026, university: "서울시립대학교", major: "스포츠과학과", name: "박O현", school: "계성고" },
  { year: 2026, university: "국민대학교", major: "스포츠산업레저학과", name: "김O수", school: "고대부고" },
  { year: 2026, university: "국민대학교", major: "스포츠산업레저학과", name: "김O원", school: "덕성여고" },
  { year: 2026, university: "숭실대학교", major: "스포츠학부", name: "박O린", school: "창문여고" },
  { year: 2026, university: "숭실대학교", major: "스포츠학부", name: "백O서", school: "성신여고" },
  { year: 2026, university: "상명대학교", major: "스포츠건강관리학과", name: "손O건", school: "송곡고" },
  { year: 2026, university: "명지대학교", major: "스포츠학부", name: "전O임", school: "이대부고" },
  { year: 2026, university: "서경대학교", major: "스포츠앤테크놀로지", name: "이O", school: "서울체고" },
  { year: 2026, university: "용인대학교", major: "특수체육교육과", name: "배O휘", school: "고대부고" },
  { year: 2026, university: "단국대학교", major: "스포츠경영학과", name: "박O향", school: "혜원여고" },
  { year: 2026, university: "백석대학교", major: "스포츠과학부", name: "이O형", school: "용문고" },
  { year: 2026, university: "나사렛대학교", major: "재활스포츠학부", name: "안O우", school: "용문고" },
  { year: 2026, university: "나사렛대학교", major: "재활스포츠학부", name: "임O영", school: "용문고" },
  { year: 2026, university: "경동대학교", major: "체육학과", name: "임O휘", school: "경복고" },
  { year: 2026, university: "동서울대학교", major: "레저스포츠과", name: "이O석", school: "송곡고" },
  { year: 2026, university: "동서울대학교", major: "레저스포츠과", name: "장O준", school: "고대부고" },
  { year: 2026, university: "한양여자대학교", major: "스포츠건강관리과", name: "김O은", school: "보성여고" },
  { year: 2026, university: "한양여자대학교", major: "스포츠건강관리과", name: "김O현", school: "혜원여고" },
  { year: 2026, university: "인하대학교", major: "체육교육과", name: "김O윤", school: "가평고" },
  { year: 2026, university: "세종대학교", major: "체육학과", name: "김O성", school: "용문고" },
  { year: 2026, university: "세종대학교", major: "체육학과", name: "박O향", school: "혜원여고" },
  { year: 2026, university: "광운대학교", major: "스포츠융합과학과", name: "김O수", school: "고대부고" },
  { year: 2026, university: "광운대학교", major: "스포츠융합과학과", name: "박O기", school: "경신고" },
  { year: 2026, university: "서울여자대학교", major: "스포츠운동과학과", name: "정O림", school: "휘봉고" },
  { year: 2026, university: "가톨릭관동대학교", major: "체육교육과", name: "강O준", school: "리라아트고" },
  { year: 2026, university: "가톨릭관동대학교", major: "스포츠재활의학전공", name: "조O모", school: "반도체고" },
  { year: 2026, university: "가톨릭관동대학교", major: "스포츠레저학전공", name: "이O찬", school: "동대부고" },
  { year: 2026, university: "경기대학교", major: "스포츠과학과", name: "최O우", school: "송곡고" },
  { year: 2026, university: "순천향대학교", major: "스포츠응용산업학과", name: "박O현", school: "서울고" },
  { year: 2026, university: "수원대학교", major: "스포츠과학부", name: "전O임", school: "이대부고" },
  { year: 2026, university: "대진대학교", major: "스포츠건강과학과", name: "최O민", school: "삼각산고" },
  { year: 2026, university: "명지전문대학교", major: "사회체육과", name: "이O석", school: "송곡고" },
  { year: 2026, university: "명지전문대학교", major: "사회체육과", name: "임O휘", school: "경복고" },
  { year: 2026, university: "장안대학교", major: "생활스포츠학과", name: "김O령", school: "서울외고" },
  { year: 2026, university: "신한대학교", major: "스포츠의학과", name: "조O우", school: "용문고" },
  { year: 2026, university: "신한대학교", major: "미래스포츠융합학과", name: "조O우", school: "용문고" },
];
