/** 분점·일정·카카오만 바꾸면 랜딩/OG/키트가 같이 바뀝니다. */

export const campaign = {
  brand: "크로스 체대입시",
  brandEn: "CROSS SPORTS ACADEMY",
  tagline: "대한민국 체대입시의 표준",
  company: "(주)크로스에듀테크",
  phone: "1833-4808",
  phoneHref: "tel:1833-4808",
  kakaoUrl: "https://pf.kakao.com/_xgATxnV",
  googleFormUrl:
    "https://docs.google.com/forms/d/e/1FAIpQLScVzS3St9cVzgjY4z5UWmPJALVcKhLr3V-dWnizmmAIjNHmPQ/viewform",
  siteUrl: "https://event.crosspe.kr",
  cta: "무료 수업 신청",
  existingBranches: ["강북본점", "청량리점"],
  existingBranchLabels: ["강북 본원", "청량리점"],
  admissionYear: 2027,
  branch: {
    name: "KBS 스포츠월드점",
    shortName: "KBS스포츠월드점",
    address: "서울특별시 강서구 공항대로 376",
    landmark: "KBS스포츠월드",
    access: "5호선 발산역 5번 출구 도보 14분 · 9호선 가양역 8번 출구 도보 15분",
    accessItems: [
      { label: "5호선", value: "발산역 5번 출구 · 도보 14분" },
      { label: "9호선", value: "가양역 8번 출구 · 도보 15분" },
      { label: "버스", value: "KBS스포츠월드 정류장 하차 · 도보 3분" },
    ],
    mapQuery: "서울특별시 강서구 공항대로 376 KBS스포츠월드",
    lat: 37.5566134,
    lng: 126.8483674,
    naverMapUrl: "https://map.naver.com/p/search/서울특별시%20강서구%20공항대로%20376%20KBS스포츠월드",
    kakaoMapUrl: "https://map.kakao.com/link/map/KBS스포츠월드,37.5566134,126.8483674",
  },
  schedule: {
    start: "2026-10-01",
    end: "2026-10-31",
    time: "19:00–21:30",
    timeLabel: "저녁 7시–9시 30분",
    daysPick: 3,
    daysHint: "월–금 중 3일. 상담 때 확정합니다.",
    place: "KBS 스포츠월드점",
  },
  offer: {
    headline: "10월 한 달, 전 수업 무료",
    subhead: "크로스 체대입시 신규 지점 오픈 기념",
    freeLabel: "10월 한 달, KBS스포츠월드점 전 수업 무료",
    freeStart: "2026-10-01",
    freeEnd: "2026-10-31",
    paidStart: "2026-11-01",
  },
  hero: {
    kicker: "크로스 체대입시 KBS스포츠월드점 오픈",
    line: "크로스 체대입시 신규 지점 오픈 기념",
    headline: "10월 한 달,\n전 수업 무료",
    support: "10월 1일부터 정규 수업이 시작됩니다. 한 달은 수강료가 없고, 등록은 11월에 선택하면 됩니다.",
  },
  why: {
    title: "왜 크로스 체대입시인가?",
    body: "압도적인 강사진과 시설, 그리고 결과로 증명합니다.",
    lead: "체대입시는 분위기 학원이 아닙니다. 종목을 나눌 강사, 시험장과 같은 측정, 그리고 합격 숫자만이 남습니다. 크로스는 그 셋을 본원 기준으로 맞춰 둡니다.",
    stats: [
      { n: "26", unit: "년", label: "검증된 커리큘럼", hint: "한 시즌용 프로그램이 아닙니다." },
      { n: "26", unit: "명", label: "전국 최다 규모 강사진", hint: "종목과 학교를 나눠 붙일 규모." },
      { n: "86", unit: "명", label: "최근 2년 대학 합격", hint: "2025·2026, 두 시즌의 결과." },
    ],
  },
  manpower: {
    title: "최강의 맨파워",
    kicker: "전국 최다 강사진",
    lead: "한 명의 만능 코치에게 여섯 종목을 맡기지 않습니다. 26명의 강사진이 종목과 희망 학교를 나눠 봅니다.",
    campuses: [
      { name: "강북본점", tag: "본원" },
      { name: "청량리점", tag: "기존" },
      { name: "KBS점", tag: "신규" },
    ],
    points: [
      {
        title: "본원 포함 3개 지점",
        body: "강북본점, 청량리점, 새로 여는 KBS점. 세 곳이 같은 강사진 네트워크를 씁니다. 분점이어도 기준은 본원입니다.",
      },
      {
        title: "전국 최다 규모 강사 포진",
        body: "숫자만 많은 학원이 아닙니다. 메디신볼과 멀리뛰기를 같은 코치가 보지 않아도 될 만큼, 종목을 쪼갤 수 있는 규모입니다.",
      },
      {
        title: "종목·학교별 맞춤 지도",
        body: "희망 대학의 배점과 종목이 다릅니다. 기록만 올리는 수업이 아니라, 그 학교의 실기 기준에 맞춰 붙입니다.",
      },
      {
        title: "본원 출신 베테랑",
        body: "크로스 본원에서 수십 년 합격 노하우를 전수받은 강사진입니다. KBS점에서 듣는 수업도 본원의 손입니다.",
      },
    ],
  },
  measure: {
    title: "실전형 환경",
    kicker: "100% 디지털 측정",
    body: "감각으로 때우는 코칭은 시험장에서 통하지 않습니다. 모든 측정 기구를 최신식으로 갖추고, 대학 입시 현장과 같은 기준으로 측정합니다.",
    closer: "실제 대학교 입시 현장과 100% 유사한 환경에서 훈련합니다.",
    closerSub: "장비만 비슷하면 끝이 아닙니다. 측정 규정, 동작 기준, 기록 내는 방식까지 시험장과 같게 맞춥니다.",
    closerImage: "/images/facility/exam-hall.jpg",
  },
  instructor: {
    name: "조샘",
    channel: "체대TV",
    years: 30,
    focus: "제자리멀리뛰기 직강",
    kicker: "스타 강사 직강",
    title: "제자리멀리뛰기의 신, 조샘",
    body: "유튜브 체대TV로 이미 본 얼굴입니다. 30년 경력의 베테랑 조샘이 KBS스포츠월드점에서 제자리멀리뛰기를 직접 지도합니다.",
    body2:
      "실기에서 가장 비중이 높고, 가장 어려운 종목입니다. 기초 메커니즘부터 만점 구간에서 쓰는 실전 팁까지, 영상에서 아끼던 부분을 수업에서 풀어 줍니다.",
  },
  elite: {
    title: "소수정예",
    lead: "기초는 동작을 고정하는 시간이고, 종목은 기록을 올리는 시간입니다. 사람이 많으면 둘 다 무너집니다.",
    body: "10명이 넘는 다수:1 수업은 하지 않습니다. 한 타임에 손이 가는 인원을 정해 두고, 그 선을 넘기지 않습니다.",
    items: [
      {
        n: "2:1",
        count: 2,
        label: "기초반",
        body: "동작과 측정 기준을 처음 잡을 때. 코치 한 명에 학생 둘입니다.",
      },
      {
        n: "6:1",
        count: 6,
        label: "종목 수업",
        body: "기록 구간으로 들어갔을 때. 최대 6명, 그 이상은 같은 타임에 받지 않습니다.",
      },
    ],
    reject: { n: "10+:1", count: 10, label: "하지 않습니다", body: "다수 수업은 단가가 아니라 기록이 깎입니다." },
  },
  results: {
    title: "증명된 합격 신화",
    kicker: "최근 2년 2025–2026 합격 데이터",
    n: "86",
    unit: "명",
    years: ["2025", "2026"],
    line: "총 입학생 86명 합격 성공",
    body: "지난 2년 동안에만 86명의 학생이 대학의 문을 넘었습니다. 우연이 아닙니다. 측정 데이터로 약점을 나누고, 종목별로 붙여서 만든 결과입니다.",
  },
  strategy: {
    title: "크로스만의 독보적 합격 전략",
    lead: "기초만 반복하거나, 팁만 던지고 끝내지 않습니다. 측정하고, 고치고, 매주 시험장 기준으로 다시 측정합니다.",
    items: [
      {
        n: "01",
        title: "기초부터 만점까지",
        body: "지금 체력과 동작이 어디인지 먼저 측정합니다. 그 숫자로 단계를 나누고, 기초반에서 만점 구간까지 커리큘럼을 붙입니다.",
        image: "/images/strategy/01-gym.png",
        pos: "object-center",
      },
      {
        n: "02",
        title: "실전 팁 전수",
        body: "30년 현장에서 쌓인 디테일입니다. 각도, 타이밍, 턴. 기록 한 구간을 올리는 스킬을 수업에서 바로 씁니다.",
        image: "/images/strategy/02-coaching.png",
        pos: "object-[center_70%]",
      },
      {
        n: "03",
        title: "주기적 테스트",
        body: "매주 실제 입시와 같은 규정으로 모의 테스트를 합니다. 감이 좋아진 게 아니라, 기록이 움직였는지를 남깁니다.",
        image: "/images/strategy/03-drill.png",
        pos: "object-[center_40%]",
      },
      {
        n: "04",
        title: "개인 맞춤 피드백",
        body: "전 종목을 영상으로 남기고, 슬로모션으로 동작을 쪼갭니다. 같은 반이어도 고칠 포인트는 학생마다 다릅니다.",
        image: "/images/strategy/04-stretch.png",
        pos: "object-[center_45%]",
      },
    ],
  },
  network: {
    title: "크로스 네트워크",
    badge: "NEW",
    headline: "KBS스포츠월드점 오픈",
    body: "1개월 무료 프로모션은 신규 지점에서만 진행됩니다. 최신 장비와 본원과 같은 강사진 기준을, 새로 연 공간에서 먼저 경험하세요.",
    existingLabel: "기존 지점",
    closer: "모든 지점은 동일한 교육 퀄리티와 강사진 네트워크를 공유합니다. 분점 수업이 본원 수업보다 얇아지지 않습니다.",
    campuses: [
      {
        name: "KBS 스포츠월드점",
        tag: "신규",
        note: "10월 전면 무료 · 최신 측정 장비",
        image: "/images/facility/kbs-studio.jpg",
        pos: "object-[center_45%]",
        featured: true,
      },
      {
        name: "강북 본원",
        tag: "본원",
        note: "합격 노하우의 기준점",
        image: "/images/facility/gangbuk.jpg",
        pos: "object-center",
        featured: false,
      },
      {
        name: "청량리점",
        tag: "기존",
        note: "본원과 같은 강사진 네트워크",
        image: "/images/facility/cheongnyangni.jpg",
        pos: "object-[72%_center]",
        featured: false,
      },
    ],
  },
  apply: {
    kicker: "1개월 무료 수업 사전 예약",
    headline: "10월 한 달, KBS스포츠월드점 전 수업 무료",
    inquiry: "문의사항",
    body: "체험 한 타임이 아닙니다. 10월 정규 수업을 무료로 듣고, 등록은 11월에 선택하면 됩니다. 강제 결제 없습니다.",
    points: ["신규 지점만 10월 무료", "평일 19:00–21:30", "하루 안에 연락"],
  },
  proof: ["체대TV 조샘 직강", "입시 현장 100%", "디지털 측정 6종"],
  events: [
    "메디신볼 던지기",
    "윗몸일으키기",
    "제자리멀리뛰기",
    "서전트 점프",
    "왕복달리기",
    "사이드스텝",
    "기타 / 상담 후 결정",
  ],
  eventTiles: [
    {
      n: "01",
      name: "메디신볼 던지기",
      measure: "상체 파워 · 협응력",
      tip: "상체 파워는 각도에서 갈린다",
      image: "/images/events/01-medicine-ball.jpg",
      pos: "object-center",
    },
    {
      n: "02",
      name: "윗몸일으키기",
      measure: "코어 근지구력",
      tip: "개수가 아니라 규정 동작이다",
      image: "/images/events/02-sit-up.jpg",
      pos: "object-[center_42%]",
    },
    {
      n: "03",
      name: "제자리멀리뛰기",
      measure: "폭발력 · 하체",
      tip: "30년 조샘이 직접 본다",
      image: "/images/events/03-long-jump.jpg",
      pos: "object-[center_40%]",
      badge: "조샘 직강",
    },
    {
      n: "04",
      name: "서전트 점프",
      measure: "수직 도약",
      tip: "체공이 아니라 도달 높이다",
      image: "/images/events/04-sergeant-jump.jpg",
      pos: "object-center",
    },
    {
      n: "05",
      name: "왕복달리기",
      measure: "민첩성 · 순발력",
      tip: "0.01초는 턴에서 나온다",
      image: "/images/events/05-shuttle-run.jpg",
      pos: "object-center",
    },
    {
      n: "06",
      name: "사이드스텝",
      measure: "측면 민첩성",
      tip: "보폭보다 중심 이동이다",
      image: "/images/events/06-side-step.jpg",
      pos: "object-[center_45%]",
    },
  ],
  weekdays: ["월", "화", "수", "목", "금"],
  faq: [
    {
      q: "진짜 무료인가요?",
      a: "네! 신규 오픈하는 KBS점 단독 프로모션으로 10월 1일 ~ 31일까지 수강료 0원에 실전 수업을 체험하실 수 있습니다. (의무 등록 조건 없음)",
    },
    {
      q: "무료 수업이 끝나면 어떻게 되나요?",
      a: "체험 종료 후 본인 희망에 따라 정규반으로 전환 가능하며, 사전 예약자에 한해 혜택이 있을 수 있습니다.",
    },
    {
      q: "KBS점 시설이 본점과 다른가요?",
      a: "본점의 30년 합격 노하우를 그대로 가져왔으며, 모든 측정 기구가 새 제품으로 구비되어 있습니다.",
    },
    {
      q: "고3 학생만 수업을 들을 수 있나요?",
      a: "아닙니다! 고1~고3 재학생은 물론 N수생, 반수생까지 체대 입시 실기를 준비하는 수험생이라면 누구나 수강할 수 있습니다.",
    },
    {
      q: "정원에 제한이 있나요?",
      a: "네, 크로스는 대규모 집체 수업 대신 밀착 케어를 위해 클래스별 정원이 있습니다. (약 40명) 선호 요일은 빠르게 마감될 수 있으니 빠른 예약을 권장합니다.",
    },
    {
      q: "실기 기초나 체력이 전혀 없는 초보자도 괜찮나요?",
      a: "물론입니다! 개인별 체력 수준을 분석하여 기초 메커니즘부터 만점 기준까지 1:1 맞춤 커리큘럼과 피드백을 제공합니다.",
    },
    {
      q: "사전 예약 및 상담은 어떻게 신청하나요?",
      a: "상단의 무료 수업 신청 버튼을 눌러 간단한 상담폼을 작성해 주시면 담당 강사가 순차적으로 확인한 후 연락 드립니다. 신청 전 고민이 되시거나 궁금한 점이 있다면 언제든 편하게 학원으로 전화 주세요! 친절하게 상담해 드립니다.",
    },
  ],
  grades: ["중3", "고1", "고2", "고3", "N수", "검정고시"],
} as const;

export type Campaign = typeof campaign;
export type Weekday = (typeof campaign.weekdays)[number];
